### ISSUE TITLE
无法正确加载您给出的训练结果

### ISSUE THREAD

**Issue by money6651626** [ChengxiHAN/HANet-CD#3]
Traceback (most recent call last):
  File "Output_Results.py", line 39, in <module>
    model = torch.load(path)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 1046, in _load
    result = unpickler.load()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 1039, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models.MSPSNetHCX'
我在加载您的训练结果模型时出现了以下情况，似乎在您的训练结果之后还修改过代码结构，不知道您是否方便更新代码，或者给我字典形式的模型参数

**Comment by money6651626** [comment]
如果您方便的话可以直接提供HAN的训练权重pth，因为我看在open-cd的复现中直接引用了该类，这应该是您的最终版本），如果这是您论文上指标用的模型。（您通过torch.save(model.state_dict())的方式来重新保存权重，我通过torch.load_state_dict(torch.load("pth"))的方式直接按照键值对加载权重，这样不会受目录结构影响）

**Comment by work1-shekhaman** [comment]
@ChengXIhan, did you found out, how to solve it, i am still facing this issue

**Comment by ChengxiHAN** [comment]
> @ChengxiHAN, did you found out, how to solve it, i am still facing this issue

sorry, bro, it needs you to train HANet again.  I haven't solved the problem yet.

**Comment by work1-shekhaman** [comment]
> > @ChengxiHAN, did you found out, how to solve it, i am still facing this issue
> 
> sorry, bro, it needs you to train HANet again. I haven't solved the problem yet.


If I train the model with batch size 4, predictions are in shape of (4,2,256,256) (for image size of (256,256))


Shape of tensor of predictions: torch.Size([4, 2, 256, 256])
Shape of tensor of target: torch.Size([1, 256, 256])
epoch 0 info 0 - 4:   0%|                                                                                            | 0/1245 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "trainHCX.py", line 157, in <module>
    cd_loss = criterion(cd_preds, labels)
  File "/root/anaconda3/envs/hanet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/c/Users/91635/Desktop/Elm/gitrepo/HANet-CD-main/HANet-CD-main/utils/losses.py", line 96, in forward
    bce = self.focal(predictions[0], target)
  File "/root/anaconda3/envs/hanet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/c/Users/91635/Desktop/Elm/gitrepo/HANet-CD-main/HANet-CD-main/utils/losses.py", line 40, in forward
    logpt = logpt.gather(1, target)
RuntimeError: Size does not match at dimension 0 expected index [262144, 1] to be smaller than self [512, 256] apart from dimension 1

**Comment by hexers123** [comment]
> > > ，你发现了吗，怎么解决呢，我仍然面临这个问题
> > 
> > 
> > 对不起，兄弟，它需要你再次训练 HANet。我还没有解决这个问题。
> 
> 如果我用批量大小 4 训练模型，则预测的形状为 （4,2,256,256）（对于图像大小 （256,256））
> 
> 预测张量的形状：torch。Size（[4， 2， 256， 256]） 目标张量的形状：torch。大小（[1， 256， 256]） epoch 0 info 0 - 4： 0%| |0/1245 [00：01<?, ?it/s] 回溯（最近调用最后一次）：文件“trainHCX.py”，第 157 行，cd_loss = criterion（cd_preds， labels） 文件“/root/anaconda3/envs/hanet/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1130 行，_call_impl返回 forward_call（*input， **kwargs） 文件“/mnt/c/Users/91635/Desktop/Elm/gitrepo/HANet-CD-main/HANet-CD-main/utils/losses.py”，第 96 行， 在前向 bce = self.focal（predictions[0]， target） 文件 “/root/anaconda3/envs/hanet/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1130 行，_call_impl返回 forward_call（*input， **kwargs） 文件 “/mnt/c/Users/91635/Desktop/Elm/gitrepo/HANet-CD-main/HANet-CD-main/utils/losses.py”，第 40 行，在前向 logpt = logpt.gather（1， target） 中RuntimeError：大小在维度 0 处不匹配，预期索引 [262144， 1] 小于维度 1 之外的自身 [512， 256]

me too

**Comment by Hank-user** [comment]
> > > > ，你发现了吗，怎么解决呢，我仍然面临这个问题
> > > 
> > > 
> > > 对不起，兄弟，它需要你再次训练 HANet。我还没有解决这个问题。
> > 
> > 
> > 如果我用批量大小 4 训练模型，则预测的形状为 （4,2,256,256）（对于图像大小 （256,256））
> > 预测张量的形状：torch。Size（[4， 2， 256， 256]） 目标张量的形状：torch。大小（[1， 256， 256]） epoch 0 info 0 - 4： 0%| |0/1245 [00：01<?, ?it/s] 回溯（最近调用最后一次）：文件“trainHCX.py”，第 157 行，cd_loss = criterion（cd_preds， labels） 文件“/root/anaconda3/envs/hanet/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1130 行，_call_impl返回 forward_call（*input， **kwargs） 文件“/mnt/c/Users/91635/Desktop/Elm/gitrepo/HANet-CD-main/HANet-CD-main/utils/losses.py”，第 96 行， 在前向 bce = self.focal（predictions[0]， target） 文件 “/root/anaconda3/envs/hanet/lib/python3.8/site-packages/torch/nn/modules/module.py”，第 1130 行，_call_impl返回 forward_call（*input， **kwargs） 文件 “/mnt/c/Users/91635/Desktop/Elm/gitrepo/HANet-CD-main/HANet-CD-main/utils/losses.py”，第 40 行，在前向 logpt = logpt.gather（1， target） 中RuntimeError：大小在维度 0 处不匹配，预期索引 [262144， 1] 小于维度 1 之外的自身 [512， 256]
> 
> me too

me too Have you solved it? Can you tell me how to solve it
