### ISSUE TITLE
No module named 'models.MSPSNetHCX'

### ISSUE THREAD

**Issue by yxzz1121** [ChengxiHAN/HANet-CD#5]
Traceback (most recent call last):
  File "E:\Futherstudy\change-detection\reproduction\HANet-CD-main\test.py", line 36, in <module>
    model = torch.load(path)
  File "D:\ANACONDA\envs\d2l\lib\site-packages\torch\serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\ANACONDA\envs\d2l\lib\site-packages\torch\serialization.py", line 1049, in _load
    result = unpickler.load()
  File "D:\ANACONDA\envs\d2l\lib\site-packages\torch\serialization.py", line 1042, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models.MSPSNetHCX'

Process finished with exit code 1

**Comment by minyeo** [comment]
me too

**Comment by dpt000121** [comment]
me too.

**Comment by 1aozh1q1ng** [comment]
m2

**Comment by dpt000121** [comment]
> m2

自己重新训练一遍就好了
